backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  accept_roles: #optional - accepts all users if left out
    - admin

local_backend: true # BETA: allows for local git repo vs the hosted version
media_folder: "static/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "blogArticles"
    label: "Blog Articles"
    folder: "cms/blogs"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blogs",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - {
          label: "Featured Image",
          name: "featuredImage",
          widget: image,
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "Tags"
        name: "tagIDs"
        widget: relation
        collection: "tags"
        displayFields: ["title"]
        searchFields: ["title"]
        valueField: "id"
        multiple: true
  - name: "tags"
    label: "Blog Tags"
    folder: "cms/tags"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "tags",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "ID", name: "id", widget: "ncw-id" }
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "homePage"
        file: "cms/pages/home.md"
        fields:
          - {
              label: Template Key,
              name: templateKey,
              widget: hidden,
              default: "home-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Hero Video, name: heroVideo, widget: file }
          - { label: Body, name: body, widget: markdown }
          - label: "Banner Image"
            name: "bannerImg"
            widget: "image"
            allow_multiple: false
            required: false
          - label: "Highlights"
            name: "highlights"
            widget: "list"
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Content, name: content, widget: string }
      - label: "Blog Page"
        name: "blogPage"
        file: "cms/pages/blog.md"
        fields:
          - {
              label: Template Key,
              name: templateKey,
              widget: hidden,
              default: "blog-page",
            }
          - { label: Title, name: title, widget: string }
          - label: "Hero Image"
            name: "heroImg"
            widget: "image"
            allow_multiple: false
            required: true
      - label: "Not Found Page"
        name: "notFoundPage"
        file: "cms/pages/404.md"
        fields:
          - {
              label: Template Key,
              name: templateKey,
              widget: hidden,
              default: "404-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string }
      - label: "Thank You Page"
        name: "thanksPage"
        file: "cms/pages/thanks.md"
        fields:
          - {
              label: Template Key,
              name: templateKey,
              widget: hidden,
              default: "thanks-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string }
  - label: "Sitewide"
    name: "sitewide"
    files:
      - label: "Header"
        name: "header"
        file: "cms/sitewide/header.md"
        fields:
          - {
              label: Template Key,
              name: templateKey,
              widget: hidden,
              default: "header",
            }
          - label: "Links"
            name: "links"
            widget: "list"
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Link, name: link, widget: string }
      - label: "Footer"
        name: "footer"
        file: "cms/sitewide/footer.md"
        fields:
          - {
              label: Template Key,
              name: templateKey,
              widget: hidden,
              default: "footer",
            }
          - { label: Contact Title, name: contactTitle, widget: string }
          - { label: Contact Content, name: contactContent, widget: text }
          - { label: Visit Title, name: visitTitle, widget: string }
          - {
              label: "Attribution",
              name: "mdAttribution",
              widget: "markdown",
              minimal: true,
            }
